<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="$(MicrosoftIdentityModelVersion)" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="$(MicrosoftIdentityModelVersion)" />
        <PackageReference Include="Microsoft.IdentityModel.Xml" Version="$(MicrosoftIdentityModelVersion)" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Protocols.WsAddressing\Protocols.WsAddressing.csproj" />
      <ProjectReference Include="..\Protocols.WsFederation\Protocols.WsFederation.csproj" />
      <ProjectReference Include="..\Protocols.WsPolicy\Protocols.WsPolicy.csproj" />
      <ProjectReference Include="..\Protocols.WsSecureConversation\Protocols.WsSecureConversation.csproj" />
      <ProjectReference Include="..\Protocols.WsSecurity\Protocols.WsSecurity.csproj" />
      <ProjectReference Include="..\Protocols.XmlEnc\Protocols.XmlEnc.csproj" />
      <ProjectReference Include="..\Protocols.WsStar\Protocols.WsStar.csproj" />
    </ItemGroup>
</Project>
